"""
Tests for enum generators (C++ and Java).
"""

from pathlib import Path

import pytest

from protocol_codegen.core.enum_def import EnumDef
from protocol_codegen.generators.common.cpp.enum_generator import generate_enum_hpp
from protocol_codegen.generators.common.java.enum_generator import generate_enum_java


class TestCppEnumGenerator:
    """Tests for C++ enum generator."""

    @pytest.fixture
    def simple_enum(self) -> EnumDef:
        """Create a simple enum for testing."""
        return EnumDef(
            name="TrackType",
            values={"AUDIO": 0, "INSTRUMENT": 1, "GROUP": 2},
            description="Type of track in Bitwig",
        )

    @pytest.fixture
    def bitflags_enum(self) -> EnumDef:
        """Create a bitflags enum for testing."""
        return EnumDef(
            name="ChildType",
            values={"NONE": 0, "SLOTS": 1, "LAYERS": 2, "DRUMS": 4},
            is_bitflags=True,
            description="Child type flags (combinable)",
        )

    def test_generates_enum_class(self, simple_enum: EnumDef) -> None:
        """Test generating a simple enum class."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "enum class TrackType : uint8_t" in code
        assert "AUDIO = 0," in code
        assert "INSTRUMENT = 1," in code
        assert "GROUP = 2," in code

    def test_generates_conversion_helpers(self, simple_enum: EnumDef) -> None:
        """Test that conversion helpers are generated."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "toTrackType(uint8_t value)" in code
        assert "fromTrackType(TrackType value)" in code
        assert "static_cast<TrackType>(value)" in code
        assert "static_cast<uint8_t>(value)" in code

    def test_no_namespace_by_default(self, simple_enum: EnumDef) -> None:
        """Test that no namespace is generated by default."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "namespace " not in code

    def test_generates_custom_namespace(self) -> None:
        """Test custom namespace."""
        enum = EnumDef(
            name="Custom",
            values={"A": 0},
            cpp_namespace="MyNamespace",
        )
        code = generate_enum_hpp(enum, Path("Custom.hpp"))

        assert "namespace MyNamespace {" in code
        assert "}  // namespace MyNamespace" in code

    def test_generates_header_comment(self, simple_enum: EnumDef) -> None:
        """Test header comment."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "AUTO-GENERATED - DO NOT EDIT" in code
        assert "TrackType.hpp" in code

    def test_generates_description_comment(self, simple_enum: EnumDef) -> None:
        """Test description in comment."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "Type of track in Bitwig" in code

    def test_generates_bitflags_constants(self, bitflags_enum: EnumDef) -> None:
        """Test generating bitflags as constants."""
        code = generate_enum_hpp(bitflags_enum, Path("ChildType.hpp"))

        # Should NOT have enum class
        assert "enum class ChildType" not in code

        # Should have constexpr constants
        assert "constexpr uint8_t CHILD_TYPE_NONE = 0;" in code
        assert "constexpr uint8_t CHILD_TYPE_SLOTS = 1;" in code
        assert "constexpr uint8_t CHILD_TYPE_LAYERS = 2;" in code
        assert "constexpr uint8_t CHILD_TYPE_DRUMS = 4;" in code

    def test_bitflags_note_in_header(self, bitflags_enum: EnumDef) -> None:
        """Test that bitflags note is in header."""
        code = generate_enum_hpp(bitflags_enum, Path("ChildType.hpp"))

        assert "bitflags" in code

    def test_includes_pragma_once(self, simple_enum: EnumDef) -> None:
        """Test pragma once is included."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "#pragma once" in code

    def test_includes_cstdint(self, simple_enum: EnumDef) -> None:
        """Test cstdint is included."""
        code = generate_enum_hpp(simple_enum, Path("TrackType.hpp"))

        assert "#include <cstdint>" in code


class TestJavaEnumGenerator:
    """Tests for Java enum generator."""

    @pytest.fixture
    def simple_enum(self) -> EnumDef:
        """Create a simple enum for testing."""
        return EnumDef(
            name="TrackType",
            values={"AUDIO": 0, "INSTRUMENT": 1, "GROUP": 2},
            description="Type of track in Bitwig",
        )

    @pytest.fixture
    def bitflags_enum(self) -> EnumDef:
        """Create a bitflags enum for testing."""
        return EnumDef(
            name="ChildType",
            values={"NONE": 0, "SLOTS": 1, "LAYERS": 2, "DRUMS": 4},
            is_bitflags=True,
        )

    def test_generates_java_enum(self, simple_enum: EnumDef) -> None:
        """Test generating a Java enum."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "public enum TrackType" in code
        assert "AUDIO(0)" in code
        assert "INSTRUMENT(1)" in code
        assert "GROUP(2)" in code

    def test_generates_get_value_method(self, simple_enum: EnumDef) -> None:
        """Test getValue method is generated."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "public int getValue()" in code
        assert "return value;" in code

    def test_generates_from_value_method(self, simple_enum: EnumDef) -> None:
        """Test fromValue method is generated."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "public static TrackType fromValue(int value)" in code
        assert "for (TrackType e : values())" in code
        assert "return AUDIO;" in code  # Default value

    def test_generates_package(self, simple_enum: EnumDef) -> None:
        """Test package declaration."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "package protocol;" in code

    def test_generates_custom_package(self) -> None:
        """Test custom package."""
        enum = EnumDef(
            name="Custom",
            values={"A": 0},
            java_package="com.example",
        )
        code = generate_enum_java(enum, Path("Custom.java"))

        assert "package com.example;" in code

    def test_generates_from_string(self) -> None:
        """Test fromString method when string_mapping is provided."""
        enum = EnumDef(
            name="DeviceType",
            values={"UNKNOWN": 0, "AUDIO_EFFECT": 1, "INSTRUMENT": 2},
            string_mapping={
                "audio-effect": "AUDIO_EFFECT",
                "instrument": "INSTRUMENT",
            },
        )
        code = generate_enum_java(enum, Path("DeviceType.java"))

        assert "public static DeviceType fromString(String str)" in code
        assert 'case "audio-effect": return AUDIO_EFFECT;' in code
        assert 'case "instrument": return INSTRUMENT;' in code
        assert "default: return UNKNOWN;" in code

    def test_no_from_string_without_mapping(self, simple_enum: EnumDef) -> None:
        """Test fromString is not generated without mapping."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "fromString" not in code

    def test_generates_bitflags_class(self, bitflags_enum: EnumDef) -> None:
        """Test generating bitflags as a final class."""
        code = generate_enum_java(bitflags_enum, Path("ChildType.java"))

        # Should NOT have enum
        assert "public enum ChildType" not in code

        # Should have final class with constants
        assert "public final class ChildType" in code
        assert "public static final int NONE = 0;" in code
        assert "public static final int SLOTS = 1;" in code
        assert "public static final int LAYERS = 2;" in code
        assert "public static final int DRUMS = 4;" in code

    def test_bitflags_private_constructor(self, bitflags_enum: EnumDef) -> None:
        """Test bitflags class has private constructor."""
        code = generate_enum_java(bitflags_enum, Path("ChildType.java"))

        assert "private ChildType() {}" in code

    def test_generates_header_comment(self, simple_enum: EnumDef) -> None:
        """Test header comment."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "AUTO-GENERATED - DO NOT EDIT" in code
        assert "TrackType.java" in code

    def test_generates_description_comment(self, simple_enum: EnumDef) -> None:
        """Test description in comment."""
        code = generate_enum_java(simple_enum, Path("TrackType.java"))

        assert "Type of track in Bitwig" in code
